apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-deployment
  labels:
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.4
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: rootpass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: password
        volumeMounts:
        - name: init-volume
          mountPath: /data/application/init.sql
      volumes:
      - name: init-volume
        hostPath:
          path: ./init.sql
          type: File

---

apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
