apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-deployment
  labels:
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      volumes:
      - name: init-volume
        hostPath:
          path: /data/application
          type: DirectoryOrCreate
      - name: maria-initdb
        configMap:
          name: maria-init
      containers:
      - image: mariadb:10.4
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: rootpass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: password
        volumeMounts:
        - mountPath: /data/application
          name: init-volume
        - mountPath: /docker-entrypoint-initdb.d
          name: maria-initdb
---

apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: ConfigMap
metadata:
    name: maria-init
data:
    initdb.sql: |
CREATE DATABASE IF NOT EXISTS mydb;
/* CREATE USER IF NOT EXISTS 'user' @'%' IDENTIFIED BY 'password'; */
GRANT SELECT,
  UPDATE,
  INSERT ON mydb.* TO 'user' @'%';
FLUSH PRIVILEGES;
USE mydb;
/*
 It appends on every run which is not initially expected.
 Dropping.
 */
DROP TABLE IF EXISTS regions;
CREATE TABLE IF NOT EXISTS regions (
  region VARCHAR(100) NOT NULL,
  maincity VARCHAR(50) NOT NULL,
  population INT (10) NOT NULL
);
INSERT INTO regions (region, maincity, population)
VALUES (
    'New York',
    'New York City',
    '8398748'
  ),
  (
    'Pennsylvania',
    'Philadelphia',
    '1584138'
  ),
  (
    'Massachusetts',
    'Boston',
    '694583'
  ),
  ('New Jersey', 'Newark', '282090'),
  (
    'Connecticut',
    'Hartford',
    '123400'
  ),
  (
    'Maryland',
    'Baltimore',
    '602495'
  ),
  ('Virginia', 'Richmond', '228783'),
  (
    'North Carolina',
    'Raleigh',
    '469298'
  );
