apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-deployment
  labels:
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
      volumes:
      - name: init-volume
        hostPath:
          path: /data/application
          type: DirectoryOrCreate
      - name: maria-initdb
        configMap:
          name: maria-init
      containers:
      - image: mariadb:10.4
        name: mariadb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: rootpass
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: maria-secret
              key: password
        volumeMounts:
        - mountPath: /data/application
          name: init-volume
        - mountPath: /docker-entrypoint-initdb.d
          name: maria-initdb
---

apiVersion: v1
kind: Service
metadata:
  name: maria-service
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

