apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      volumes:
      - name: php-files
        hostPath:
          path: /var/www/html
          type: DirectoryOrCreate
      containers:
      - image: xelorr/php-apache-mysqli
        name: webapp
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: php-files

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234
