apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: xelorr/php-apache-mysqli
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-files
          mountPath: /var/www/html
      volumes:
      - name: php-files
        hostPath:
          path: ./src
          type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 34567
